---
apiVersion: apps/v1
kind:       Deployment
metadata:
  name:      grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name:            grafana
        image:           grafana/grafana
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu:    100m
            memory: 200Mi
          limits:
            cpu:    800m
            memory: 400Mi
        ports:
        - name:          http
          containerPort: 3000
        volumeMounts:
        - name:      prom-ds
          mountPath: /etc/grafana/provisioning/datasources
        - name:      prom-dash
          mountPath: /etc/grafana/provisioning/dashboards
        - name:      hm-dash
          mountPath: /etc/grafana-dash
      volumes:
        - name: prom-ds
          configMap:
            name: prom-ds
        - name: prom-dash
          configMap:
            name: prom-dash
        - name: hm-dash
          configMap:
            name: hm-dash
---
kind:       Service
apiVersion: v1
metadata:
  name:      grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name:       http
      protocol:   TCP
      nodePort:   30300
      port:       3000
