---
# Deployment
kind:       Deployment
apiVersion: apps/v1
metadata:
  name: north
spec:
  replicas: 1
  selector:
    matchLabels:
      org:  g.o.t
      clan: north
  template:
    metadata:
      labels:
        org:  g.o.t
        clan: north
    spec:
      containers:
      - name:            north
        image:           k8sland/north-svc-go:0.0.1
        imagePullPolicy: IfNotPresent
        args:            ["/app/north", "--url", "castleblack:4000"]
        resources:
          requests:
            cpu:    100m
            memory: 25Mi
          limits:
            cpu:    200m
            memory: 50Mi
        ports:
        - name:          http
          containerPort: 4005
---
# Service
kind:       Service
apiVersion: v1
metadata:
  name: north
spec:
  type: NodePort
  selector:
    org:  g.o.t
    clan: north
  ports:
    - name:       http
      protocol:   TCP
      nodePort:   30501
      port:       4005
